apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: staging
spec:
  selector:
    app: nodejs-app
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}

