---
- name: Create pods using deployment 
  hosts: kubernetes 
  # become: true
  user: ubuntu
 
  tasks: 
  - name: deploy application via Helm chart
    command: helm install sample-nodejs-app ./nodejs-app-helm/ --set service.type=NodePort
